name: NoteGoat CI/CD
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: npm i
      - run: npm i -g serverless
      - run: pip install pipenv
      - run: ./bin/01-deploy.sh
